language: generic
sudo: required
dist: trusty
cache:
  directories:	
    - RakNet		
    - flatbuffers		
    - bin/CMakeFiles/
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - kalakris-cmake
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - p7zip
            - cmake
            - cmake-data
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - freeglut3-dev
            - libglew-dev
            - libfreetype6-dev
            - libsdl2-dev
            - libsdl2-image-dev
install:
  - sudo ln -s /usr/bin/g++-6 /usr/bin/g++ -f
  - sudo cp -r /usr/include/freetype2/* /usr/include/
  - sudo cp -r /usr/include/freetype2 /usr/include/freetype
  - |
    if [ ! -f ./RakNet/cached_mark ];
    then
    git clone https://github.com/OculusVR/RakNet.git
    cd ./RakNet
    cmake .
    make
    make install
    touch cached_mark
    cd ..
    fi
  - |
    if [ ! -f ./flatbuffers/cached_mark ];
    then
    git clone https://github.com/google/flatbuffers.git
    cd ./flatbuffers
    cmake .
    make
    touch cached_mark
    cd ..
    fi
  - export NEWORLD_PATH=/home/travis/build/Infinideastudio/NEWorld
  - export CPLUS_INCLUDE_PATH=$NEWORLD_PATH/RakNet/include:$NEWORLD_PATH/flatbuffers/include/
  - export LIBRARY_PATH=$NEWORLD_PATH/flatbuffers/:$NEWORLD_PATH/RakNet/Lib/DLL/
script:
  - cd ./src/protocol
  - python ./make_fb.py ../../flatbuffers/
  - cd ../../
  - cd ./release/
  - cmake .. -Wno-dev
  - make
  - cd ..
