version: '{build}'
cache:
  - dependencies -> build\appveyor_install.bat
platform:
  - x86
  - x64
configuration:
  - Release
clone_folder: C:\NEWorld
clone_depth: 1
install:
  # Install dependencies
  - if not exist "dependencies\" .\build\appveyor_install.bat
  - dir C:\Libraries\boost
  - dir C:\Libraries\boost\boost
build:
  project: build/VisualStudio_v14/NEWorld.sln
  verbosity: minimal
on_success:
  # Create an archive
  - if %PLATFORM% equ x86 (copy .\dependencies\dll\* .\release\) else (copy .\dependencies\dll_x64\* .\release\) > nul
  - 7z a c:\NEWorld.zip .\licenses > nul
  - cd .\release
  - 7z a c:\NEWorld.zip . > nul
  - if %PLATFORM% equ x64 rename c:\NEWorld.zip NEWorld_x64.zip
  - if %PLATFORM% equ x64 (appveyor PushArtifact c:\NEWorld_x64.zip) else (appveyor PushArtifact c:\NEWorld.zip)
  
